---
- name: VALIDATE OBJECT EXISTENCE
  hosts: apic
  connection: local
  gather_facts: False
  vars_files:
     - variable_file.yaml

  tasks:
    - name: CREATE TENANT VRF
      aci_vrf:
        host: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "present"
        validate_certs: False
        tenant: "{{ tenant }}"
        vrf: "{{ vrf_name }}"
        description: "LAB VRF"

    - name:  CREATE EXTERNAL BRIDGE DOMAIN 
      aci_bd:
        host: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "present"
        validate_certs: False
        tenant: "{{ tenant }}"
        bd: "{{consumerBD_name}}"
        vrf: "{{vrf_name}}"
        description: "external BD"

    - name: CREATE EXTERNAL BRIDGE DOMAIN SUBNET
      aci_bd_subnet:
        host: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "present"
        validate_certs: False
        tenant: "{{ tenant }}"
        bd: "{{consumerBD_name}}"
        gateway: "10.1.10.1"
        mask: 24
        description: "External Subnet"

    - name: CREATE INTERNAL BRIDGE DOMAIN
      aci_bd:
        host: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "present"
        validate_certs: False
        tenant: "{{ tenant }}"
        bd: "{{providerBD_name}}"
        vrf: "{{vrf_name}}"
        description: " internal BD "

    - name: CREATE INTERNAL BRDIGE DOMAIN SUBNET
      aci_bd_subnet: 
        host: "{{ ansible_host}}" 
        username: "{{ username }}"
        password: "{{ password }}"
        state: "present"
        validate_certs: False
        tenant: "{{ tenant }}"
        bd: "{{providerBD_name}}"
        gateway: "10.1.20.1"
        mask: 24
        description: "Internal Subnet" 
