- name: Contract Setup 
  hosts: apic
  connection: local
  gather_facts: false

  vars_files:
    - variable_file.yaml

  tasks:

  - name: Create XML POSTS from templates
    template: src={{ item.src }} dest={{ item.dest }}
    with_items:
      - { src: 'unManagedMode_posts/contract00.j2',                  dest: 'unManagedMode_posts/contract00.xml' }

  - name: Create contract
    aci_rest:
      action: "post"
      uri: "/api/node/mo/uni/tn-{{ tenant }}.xml"
      config_file: "{{ item }}"
      host: "{{inventory_hostname}}"
      validate_certs: false
      username: "{{ username }}"
      password: "{{ password }}"
    with_items:
     - "unManagedMode_posts/contract00.xml"
