---
- name: VALIDATE APPLICATION EXISTENCE
  hosts: apic
  connection: local
  gather_facts: False
  vars_files:
   - variable_file.yaml

  tasks:
    - name: ENSURE APPLICATION EXISTS
      aci_ap:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "present"
        validate_certs: False
        tenant: "{{ tenant }}"
        ap: "{{ appProfile_name }}"
        descr: "LAB App Profile"

    - name: CREATE EXTERNAL EPG
      aci_epg:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "present"
        validate_certs: False
        tenant: "{{ tenant }}"
        ap: "{{ appProfile_name }}"
        epg: "{{consumerEPG_name}}"
        bd: "{{consumerBD_name}}"
        description: "External EPG"

    - name: ENSURE DOMAIN IS BOUND TO EPG
      aci_epg_to_domain:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "present"
        validate_certs: false
        tenant: "{{ tenant }}"
        ap: "{{ appProfile_name }}"
        epg: "{{consumerEPG_name}}"
        domain: "POD11-VMM-DOMAIN"
        domain_type: "vmm"
        vm_provider: "vmware"
        encap_mode: "auto"
        encap: 230 
#      with_items: "{{ epgs }}"

    - name: ENSURE EPG IS ASSOCIATED TO CONTRACTS
      aci_epg_to_contract:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "present"
        validate_certs: False
        tenant: "{{ tenant }}"
        ap: "{{ appProfile_name }}"
        epg: "{{consumerEPG_name}}"
        contract: "{{ contract_name }}"
        contract_type: "consumer"
      
    - name: CREATE INTERNAL EPG
      aci_epg:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "present"
        validate_certs: False
        tenant: "{{ tenant }}"
        ap: "{{ appProfile_name }}"
        epg: "{{providerEPG_name}}"
        bd: "{{providerBD_name}}"
        description: "Internal EPG"

    - name: ENSURE DOMAIN IS BOUND TO EPG
      aci_epg_to_domain:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "present"
        validate_certs: false
        tenant: "{{ tenant }}"
        ap: "{{ appProfile_name }}"
        epg: "{{providerEPG_name}}"
        domain: "POD11-VMM-DOMAIN"
        domain_type: "vmm"
        vm_provider: "vmware"
        encap_mode: "auto"
        encap: 23

    - name: ENSURE EPG IS ASSOCIATED TO CONTRACTS
      aci_epg_to_contract:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "present"
        validate_certs: False
        tenant: "{{ tenant }}"
        ap: "{{ appProfile_name }}"
        epg: "{{providerEPG_name}}"
        contract: "{{ contract_name }}"
        contract_type: "provider"
