- name: SERVICE GRAPH TEMPLATE TASKS
  hosts: apic
  connection: local
  gather_facts: false

  vars_files:
    - variable_file.yaml

  tasks:

  - name: Create XML POSTS from templates
    template: src={{ item.src }} dest={{ item.dest }}
    with_items:
      - { src: 'unManagedMode_posts/service_graph_template.j2',    dest: 'unManagedMode_posts/service_graph_template.xml'}

  - name: Create service graph template
    aci_rest:
      action: "post"
      uri: "/api/node/mo/uni/tn-{{tenant_name}}.xml"
      config_file: "{{ item }}"
      host: "{{inventory_hostname}}"
      validate_certs: false
      username: admin
      password: ciscopsdt
    with_items:
     - "unManagedMode_posts/service_graph_template.xml"
