
- name: CREATE POOL & POOL MEMBERS 
  hosts: bigips
  connection: local
  gather_facts: false

  vars_files:
    - variable_file.yaml

  tasks:

  - name: CREATING POOL
    bigip_pool:
        server: "{{inventory_hostname}}"
        user: "admin"
        password: "f5DEMOs4u12345"
        state: "present"
        name: "{{tenant_name}}_http-pool"
        lb_method: "round-robin"
#        monitors: "none"
        validate_certs: False
    delegate_to: localhost

  - name: ADDING POOL MEMBERS
    bigip_pool_member:
        server: "{{inventory_hostname}}"
        user: "admin"
        password: "f5DEMOs4u12345"
        pool: "{{tenant_name}}_http-pool"
        #name: "{{tenant_name}}_http-pool"
        host: "{{item.host}}"
        port: "{{item.port}}"
        validate_certs: False
    with_items: "{{pool_members}}"
    delegate_to: localhost
  

